--- #YAML:1.0
name:                CPAN-Testers-WWW-Reports-Query-Report
version:             0.03
abstract:            Retrieve CPAN Testers report direct from the CPAN Testers website.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  CPAN::Testers::Report:  0
  JSON::XS:               0
  WWW::Mechanize:         0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  CPAN::Testers::WWW::Reports::Query::Report:
    file:     lib/CPAN/Testers/WWW/Reports/Query/Report.pm
    version:  0.03

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-WWW-Reports-Query-Report
  repository: http://github.com/barbie/cpan-testers-www-reports-query-report

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Barbie's Brain 1.0
